const Shop = require("../../models/shop");
import dbConnect from "../../utils/dbConnect";

const func = async (req, res) => {
  try {
    await dbConnect();
    const shop = Shop({
      filterOne: [
        {
          name: "PRINTING",
          img: "https://cdn.pixabay.com/photo/2017/06/10/07/29/printer-2389244_960_720.png",
          cost: 1,
        },
        {
          name: "PACKAGING",
          img: "https://cdn.pixabay.com/photo/2017/02/16/13/42/box-2071537_960_720.png",
          cost: 1,
        },
      ],
      filterTwo: [
        {
          category: "PACKAGING",
          items: [
            {
              name: "BOXES",
              description: "",
              cost: 1,
              options: [
                { name: "CORROGATED BOXES", img: "", description: "", cost: 1 },
                {
                  name: "3 PLY CORROAGTED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "5 PLY CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "7 PLY CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "ECOMMERCE CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "CONTAINER BOXES", img: "", description: "", cost: 1 },
                {
                  name: "CABLE WIRE PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "MONO CARTON CUSTOM DESIGN AND PRINTED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "ECOMMERCE CUSTOMIZED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "CORROGATED FITTING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "PRINTED DUPLEX CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "FLOWER AND PLANT BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "GIFT BOX PERSONALIZED",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "PHARMA MEDICINE", img: "", description: "", cost: 1 },
                {
                  name: "MONO CARTON BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "PLASTIC CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "PLYWOOD BOXES", img: "", description: "", cost: 1 },
                {
                  name: "PRINTED BROWN CORROGATED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "RIGID BOXES", img: "", description: "", cost: 1 },
                {
                  name: "STORAGE ARCHIVED BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "BOXES ON SCALE", img: "", description: "", cost: 1 },
              ],
              img: "https://cdn.pixabay.com/photo/2016/04/01/08/49/box-1299001_960_720.png",
            },
            {
              name: "BAGS",
              description: "",
              cost: 1,
              options: [
                { name: "AIR BUBBLE BAGS", img: "", description: "", cost: 1 },
                {
                  name: "ALUMINIUM SPOUT PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "BIODEGRADABLE BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "SHRINK BAGS", img: "", description: "", cost: 1 },
                { name: "PAPER BAGS", img: "", description: "", cost: 1 },
                {
                  name: "GOLD LOAN ENVELOPES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "FOOD DELIVERY BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "D CUT CARRY BAGS", img: "", description: "", cost: 1 },
                { name: "CABLE WIRE BAGS", img: "", description: "", cost: 1 },
                { name: "SIM CARD BAGS", img: "", description: "", cost: 1 },
                { name: "FAST FOOD BAGS", img: "", description: "", cost: 1 },
                { name: "PAPER ENVELOPS", img: "", description: "", cost: 1 },
                {
                  name: "SIDE GUSSET LOOP CARRY BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "WEDDING BAGS", img: "", description: "", cost: 1 },
                { name: "STANDUP POUCHES", img: "", description: "", cost: 1 },
              ],
              img: "https://cdn.pixabay.com/photo/2013/07/13/09/47/paper-bag-156023_960_720.png",
            },
            {
              name: "CLOTHING",
              description: "",
              cost: 1,
              options: [
                { name: "WATCH PACKAGING", img: "", description: "", cost: 1 },
                { name: "SHOES PACKAGING", img: "", description: "", cost: 1 },
                { name: "BELT PACKAGING", img: "", description: "", cost: 1 },
                {
                  name: "JEWLERY PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "SHIRT/PANT PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "WOMEN ACCESSORIES",
                  img: "",
                  description: "",
                  cost: 1,
                },
              ],
              img: "https://cdn.pixabay.com/photo/2018/10/18/16/44/suitcase-3756821_960_720.png",
            },
            {
              name: "ECOMMERCE",
              description: "",
              cost: 1,
              options: [
                { name: "BOOKS PACKAGING", img: "", description: "", cost: 1 },
                {
                  name: "CUSTOM BOOKS PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "ECOMMERCE BOXES", img: "", description: "", cost: 1 },
                {
                  name: "CUSTOM MOBILE ACCESSORIES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "MOBILE ACCESSORIES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "MARKETPLACE PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "EYEWEAR PACKAGING",
                  img: "",
                  description: "",
                  cost: 1,
                },
              ],
              img: "https://cdn.pixabay.com/photo/2019/04/26/07/14/store-4156934_960_720.png",
            },
            {
              name: "FOOD BOXES",
              description: "",
              cost: 1,
              options: [
                { name: "COKE BOXES", img: "", description: "", cost: 1 },
                { name: "TEA PACKAGING", img: "", description: "", cost: 1 },
                { name: "SWEETS BOXES", img: "", description: "", cost: 1 },
                { name: "BAR PACKAGING", img: "", description: "", cost: 1 },
                {
                  name: "CUSTOM PIZZA BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "PIZZA BOXES", img: "", description: "", cost: 1 },
                { name: "EGGS PACKAGING", img: "", description: "", cost: 1 },
                { name: "CHOCOLATE BOXES", img: "", description: "", cost: 1 },
                { name: "COOKIES BOXES", img: "", description: "", cost: 1 },
                { name: "DRY FRUITS BOXES", img: "", description: "", cost: 1 },
                { name: "DONUTS BOXES", img: "", description: "", cost: 1 },
                {
                  name: "FOOD DELIVERY BOXES",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "FOOD SERVING AND CONTAINER",
                  img: "",
                  description: "",
                  cost: 1,
                },
              ],
              img: "https://cdn.pixabay.com/photo/2014/04/03/00/29/chicken-nuggets-308448_960_720.png",
            },
            {
              name: "COURIER",
              description: "",
              cost: 1,
              options: [
                {
                  name: "CUSTOM COURIER BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "PRINTED COURIER BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "THIRD PARTY LIMITED BAGS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "60 MICRON WHITE COURIER BAGS WITH POD",
                  img: "",
                  description: "",
                  cost: 1,
                },
              ],
              img: "https://cdn.pixabay.com/photo/2021/02/26/11/23/man-6051503_960_720.png",
            },
            {
              name: "STATIONARY",
              description: "",
              cost: 1,
              options: [
                { name: "PACKAGING PAPER", img: "", description: "", cost: 1 },
                { name: "PEN BOXES", img: "", description: "", cost: 1 },
              ],
              img: "https://cdn.pixabay.com/photo/2021/02/26/11/23/man-6051503_960_720.png",
            },
          ],
        },
        {
          category: "PRINTING",
          items: [
            {
              name: "DIGITAL PRINTING",
              description: "",
              cost: 1,
              options: [
                { name: "BOOKLET", img: "", description: "", cost: 1 },
                { name: "BUSINESS_CARD", img: "", description: "", cost: 1 },
                { name: "BROUCHERS", img: "", description: "", cost: 1 },
                {
                  name: "FLAT_UNFINISHED_SHEETS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "FOLDED-LEAFLETS", img: "", description: "", cost: 1 },
                { name: "GRAFTING-CARDS", img: "", description: "", cost: 1 },
                { name: "INDOOR", img: "", description: "", cost: 1 },
                {
                  name: "STICKERS-AND-LABELS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "DISPLAY-BOARDS", img: "", description: "", cost: 1 },
                { name: "TAGS", img: "", description: "", cost: 1 },
                {
                  name: "VINYLE-PVC-BANNERS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "POST-CARDS", img: "", description: "", cost: 1 },
                { name: "NOTEPADS", img: "", description: "", cost: 1 },
                { name: "CALENDARS", img: "", description: "", cost: 1 },
                { name: "MENUCARDS", img: "", description: "", cost: 1 },
              ],
              img: "https://cdn.pixabay.com/photo/2016/12/16/06/56/printer-1910685_960_720.png",
            },
            {
              name: "OFFSET PRINTING",
              img: "https://cdn.pixabay.com/photo/2018/08/27/08/47/offset-printing-macine-3634411_960_720.jpg",
              description: "",
              cost: 1,
              options: [
                { name: "BOOKS", img: "", description: "", cost: 1 },
                {
                  name: "CATALOGUE/BROUCHERS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                {
                  name: "PROMOTIONAL-MATERIALS",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "POSTERS", img: "", description: "", cost: 1 },
                { name: "REFERENCE-BOOK", img: "", description: "", cost: 1 },
                {
                  name: "PERSONALIZED-PRINTING",
                  img: "",
                  description: "",
                  cost: 1,
                },
                { name: "GIFT-BOX", img: "", description: "", cost: 1 },
                { name: "ALBUMS", img: "", description: "", cost: 1 },
                { name: "MAGAZINE", img: "", description: "", cost: 1 },
                { name: "CARD-PRINTING", img: "", description: "", cost: 1 },
                { name: "GAME-CARD", img: "", description: "", cost: 1 },
                { name: "POST-CARDS", img: "", description: "", cost: 1 },
                { name: "NOTEPADS", img: "", description: "", cost: 1 },
                { name: "CALENDARS", img: "", description: "", cost: 1 },
                { name: "MENUCARDS", img: "", description: "", cost: 1 },
              ],
            },
          ],
        },
      ],
      customization: [
        {
          category: "PACKAGING",
          options: [
            {
              name: "Select the type best matching your product",
              type: "DROP",
              cost: 1,
              values: [
                "Shoes",
                "Electronic Gadgets",
                "Carton Boxes",
                "Eatables",
              ],
            },
            {
              name: "Type of Paper",
              type: "DROP",
              cost: 1,
              values: [
                "VIRGIN CRAFT PAPER",
                "PARTLY RECYCLED LINER PAPER",
                "FULL RECYCLED LINER PAPER",
                "WASTE BASED LINER",
                "FULLY BLEACHED CRAFT LINER",
                "WHITE COATED RECYCLED LINER",
                "MOLTED WHITE CRAFT",
                "100% RECYCLED FIBRES",
              ],
            },
            {
              name: "Select paper weight and GSM",
              type: "DROP",
              cost: 1,
              values: [
                "115 - 125 GSM",
                "140-150 GSM",
                "185 - 200 GSM",
                "250 GSM",
                "300 GSM",
              ],
            },
            {
              name: "Color of paper",
              type: "DROP",
              cost: 1,
              values: ["WHITE", "BROWN", "BLACK"],
            },
            {
              name: "Print options",
              type: "DROP",
              cost: 1,
              values: ["None", "MULTI-COLOR", "SINGLE-COLOR"],
            },
            {
              name: "Shape of box",
              type: "DROP",
              cost: 1,
              values: ["RECTANGLE", "PIZZA-TYPE", "TUCK-IN"],
            },
            {
              name: "Quality of paper",
              type: "DROP",
              cost: 1,
              values: ["ECONOMY", "PREMIUM", "SUPER-PREMIUM"],
            },
            {
              name: "Coating",
              type: "DROP",
              cost: 1,
              values: [
                "THERMAL-GLOSS",
                "PVC-LAMINATION",
                "EMBOSS",
                "SILVER",
                "LEAT FULL",
                "HYBRID",
                "VANISH-COATING",
                "SPOT-UV",
                "MATT-HALF",
                "HALF-GLOSS-LAMINATION",
                "MATT-LAMINATION",
                "GLOSS-LAMINATION",
              ],
            },
            {
              name: "Enter length(inch)",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Enter breadth(inch)",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Enter height(inch)",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Upload a photo of your design",
              type: "FILE",
              cost: 1,
              values: [],
            },
          ],
        },
        {
          category: "PRINTING",
          options: [
            {
              name: "Select type of paper",
              type: "DROP",
              cost: 1,
              values: [
                "GLOSS",
                "MATTE",
                "BRIGHT-WHITE-PAPER",
                "BAND-PAPER",
                "COATED-PAPER",
                "MATTEMARKED-PAPER",
                "SATIN-PAPER",
                "DULL-PAPER",
                "MAPLITO",
              ],
            },
            {
              name: "Select GSM of paper",
              type: "DROP",
              cost: 1,
              values: [
                "52",
                "58",
                "60",
                "70",
                "150",
                "180",
                "200",
                "250",
                "300",
              ],
            },
            {
              name: "Enter length",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Enter breadth",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Enter quanitity of gloss",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Select type of grinning",
              type: "DROP",
              cost: 1,
              values: ["CTP", "GRINNING"],
            },
            {
              name: "Select paper of cover",
              type: "DROP",
              cost: 1,
              values: [
                "GLOSS",
                "MATTE",
                "BRIGHT-WHITE-PAPER",
                "BAND-PAPER",
                "COATED-PAPER",
                "MATTEMARKED-PAPER",
                "SATIN-PAPER",
                "DULL-PAPER",
                "MAPLITO",
              ],
            },
            {
              name: "Enter GSM of cover",
              type: "NUMBER",
              cost: 1,
              values: [],
            },
            {
              name: "Select cover color",
              type: "COLOR",
              cost: 1,
              values: [],
            },
            {
              name: "What kind of printing",
              type: "DROP",
              cost: 1,
              values: ["DIGITAL", "OFFSET"],
            },
            {
              name: "Select paper quality",
              type: "DROP",
              cost: 1,
              values: ["ECONOMY", "PREMIUM", "SUPER_PREMIUM"],
            },
            {
              name: "Do you want your book to be glued ?",
              type: "DROP",
              cost: 1,
              values: ["YES", "NO"],
            },
            {
              name: "What kind of cover lamination ?",
              type: "DROP",
              cost: 1,
              values: [
                "GLOSS",
                "MATTE",
                "VELVET",
                "GOLD",
                "SILVER",
                "NO_LAMINATION",
              ],
            },
            {
              name: "Select printing mechanism",
              type: "DROP",
              cost: 1,
              values: ["FOLDING", "SEWING", "SPOT-UV"],
            },
            {
              name: "Upload a photo of your design",
              type: "FILE",
              cost: 1,
              values: [],
            },
            {
              name: "Upload a link of your text/pdf file.",
              type: "TEXT",
              cost: 1,
              values: [],
            },
          ],
        },
      ],
    });
    await shop.save();
    res.send("Done");
  } catch (err) {
    res.send(err);
  }
};

export default func;
